/*
 * ObjectFileReader.h
 *
 *  Created on: Jan 20, 2016
 *      Author: littlelion
 */

#ifndef OBJECTFILEREADER_H_
#define OBJECTFILEREADER_H_

#include <cstddef>
#include <string>
#include <vector>

#include "Object3dModel.h"

namespace std {

/**
 * Reader class with capabilities to extract multiple 3D graphics objects
 * from a .obj file generated by blender.
 */
class ObjectFileReader {
	friend class Object3dModel;

public:
	ObjectFileReader(string path, bool reverseMass = false,
			bool inFileNameAsPrefix = true);
	~ObjectFileReader();

	Object3dModel read();
	bool hasNext();
	int readAll();

	void writeHfile(string folderPath, ostream* logfp = &cout);
	void writeCfile(string folderPath, ostream* logfp = &cout);
	void writeSingleHfile(string folderPath, ostream* logfp = &cout);

	vector<string> objects;       ///< names of the models
	vector<Object3dModel> models; ///< all parsed models

private:
	void init();
	inline void tokenize(const string& line, const size_t n,
			float data[], size_t p);
	void writeHeader(ofstream* fp, bool isHfile = false);
	void writeCpositions(ofstream* fp);
	void writeCtexels(ofstream* fp);
	void writeCnormals(ofstream* fp);
	void writeCmasses(ofstream* fp);
	void writeCsprings(ofstream* fp);
	void writeForwardIdx(ofstream* fp);
	void writeReverseIdx(ofstream* fp);

	string path;
	bool reverseMass;     ///< enable generation of reverse index array for position --> mass mapping
	string prefix;        ///< use input filename as prefix for object names
	size_t offset = 0;    ///< offset to read from input file
	size_t objNo = 0;     ///< the object to read
	bool isInit = false;  ///< guard for initialization
	size_t vOffs = 1;     ///< indices are continuous for all objects in the same file, store the offset here; vertices
	size_t tOffs = 1;     ///< offset for index correction: texels vector
	size_t nOffs = 1;     ///< offset for index correction: normals vector
	size_t totalVert = 0; ///< total number of vertices, valid id read task is finished (hasNext() = false)
};

} /* namespace std */

#endif /* OBJECTFILEREADER_H_ */
